### PR TITLE
fix: fix stream stuck after the underlying connection is closed

### LINKED ISSUE #259: The stream is not closed when the underlying connection closed?
Hi, I'm using tokio-yamux in my project, and this  tokio-yamux helps me a lot, thanks for this excellent lib.

I have encountered a problem.

I opened some streams, and copy the io from my served connections to those stream and also from those streams to my served connections.
I have tested an exceptional use case that when I close the server side of yamux, I expect that the copying threads should stop. but the reality is that it is still running. 

So my question is: How to stop the Read or Write of the yamux stream, when the underlying connection is closed.
I  tried to add control.close() in the "next call thread" but it is still no use.

```
tokio::spawn(async move {
                loop {
                    match agent_session.next().await {
                        Some(_) => (),
                        None => {
                            debug!("closing session");
                            health_control.close().await;
                            break;
                        }
                    }
                }
            });
```

Is it something I ignored? or are there any other suggestion for this use case?

### PR DESCRIPTION
**Pull request by driftluo**
fix #259

When the session is closed, all streams need to be set to `RemoteClosed`

### CODE REVIEW

File: yamux/src/session.rs [hunk 1]
```diff
@@ -842,4 +839,50 @@ mod test {
             )
         })
     }
+
+    #[test]
+    fn test_close_session_on_stream_opened() {
```
Comment (doitian) [inline yamux/src/session.rs:844]: 👍

Comment (doitian) [reply yamux/src/session.rs:844]: 1. Please add a link to the issue in this test case so we know the reason why the test case is added when reading the source code.
2. There's no assertions in this test case, please add a comment to explain how the test case fails before the fixing

**Review by doitian — CHANGES_REQUESTED** [review]

**Review by doitian — APPROVED** [review]

**Review by TheWaWaR — APPROVED** [review]
