### PR TITLE
fix: poll_read: wrong behavior on half close

### LINKED ISSUE #360: `read` on `StreamHandle` returns `UnexpectedEof` instead of `Ok(0)`
可能与 #205 有关。

我用`io::copy`转发数据，发现`StreamHandle`在另一端调用`shutdown`后`read`总是返回一个`unexpectedeof`，但Tokio的`TcpStream`在这种情况下返回`Ok(0)`，`io::copy`也依赖该行为，是有意这样设计的吗？

[测试代码-yamux](<https://gist.github.com/moeshinyo/d63aa8433685491b5aa56c8ab777a96f#file-tokio-yamux-io-copy-rs-L94>)
[测试代码-tokio](<https://gist.github.com/moeshinyo/adfd5401d0ef93c1697c8afbd72c291e>)

### PR DESCRIPTION
**Pull request by moeshinyo**
this fixes #360.

### 修改

- `process_flags`以前会在内部将`LocalClosing`和`Reset`状态转换到`Closed`，阻止`poll_read`观测`Closed`的来源，现在将状态保留了，`drop`部分对应`Reset`的检查也有更新。
- `check_self_state`现在返回一个`Result<Option<Result>>`，表示存在不需要读底层的流就能向用户返回数据的情况（根据约定，对EOF返回一个零长度的读）。
- 以前yamux在一端`shutdown`后，另一方向的流也会出现问题，所以放宽了`poll_read`, `poll_write`等几个函数中的一些flag检查，现在可以在`shutdown`之后继续调用`read`读取数据了。

### CODE REVIEW

File: yamux/src/stream.rs [hunk 1]
```diff
@@ -391,9 +385,7 @@ impl AsyncWrite for StreamHandle {
         buf: &[u8],
     ) -> Poll<io::Result<usize>> {
         match self.state {
-            StreamState::RemoteClosing | StreamState::Reset => {
```
Comment (driftluo) [inline yamux/src/stream.rs:394]: I think there is a problem here, when the remote a is closed, b can only read the remote data and can no longer send data to the remote

**Review by driftluo — APPROVED** [review]

File: yamux/src/stream.rs [hunk 2]
```diff
@@ -308,25 +301,25 @@ impl StreamHandle {
         Ok(())
     }
 
-    fn check_self_state(&mut self) -> Result<(), io::Error> {
+    // Returns `Ok(Some(..))` if someting out of thin air should be returned to the user.
+    // Otherwise, returns `Err(Error)` whenever unable to read bytes.
+    fn check_self_state(&mut self) -> io::Result<Option<io::Result<()>>> {
```
Comment (TheWaWaR) [inline yamux/src/stream.rs:306]:
```suggestion
    fn check_self_state(&mut self) -> io::Result<bool> {
```
I think it's not a good return type, why should `fn check_self_state()` care about what's the return value will be used?

Comment (moeshinyo) [reply yamux/src/stream.rs]: agree. updated.

**Review by TheWaWaR — APPROVED** [review]
